baseURL = "https://nrsyed.com/"
languageCode = "en-us"
title = "Najam R. Syed"
theme = "hyde-hyde"
author = "Najam R. Syed"

[markup]
  [markup.goldmark.renderer]
    unsafe = true

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Posts"
  url = "/posts/"
  weight = 20

[[menu.main]]
  name = "Projects"
  identifier = "projects"
  url = "/projects/"
  weight = 30

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 40

[[menu.main]]
  name = "Contact"
  url = "/contact/"
  weight = 50

[params]
  description = "Engineering, programming, and technical miscellanies"
  authorimage = "img/beach.jpg"

  copyright = "Najam R. Syed"
  since = 2017

[params.social]
  github = "nrsyed"
  linkedin = "najam-syed"
  youtube = "UCiCUUVapPoHckB1xdZFTHiA"
