baseURL = "https://nrsyed.com/"
languageCode = "en-us"
title = "Najam R. Syed"
theme = "uBlogger"
author = "Najam R. Syed"

[params]
  version = "1.3.X"
  description = "Engineering, programming, and assorted technical miscellanies"

  [params.header]
    desktopMode = "fixed"

    [params.header.title]
      name = "Najam R. Syed"

  [params.social]
    GitHub = "https://github.com/nrsyed"
    Linkedin = "https://www.linkedin.com/in/najam-syed/"

  [params.page]
    theme = "classic"

    [params.page.toc]
      enable = false

[markup.goldmark.renderer]
  unsafe = true
